# -*- coding: utf-8 -*-
# Descriptive names for the pattern library. The source archive numbers patterns only;
# these names describe what each pattern actually does so they can be told apart.
NAMES = {
"beginner-1":"Kick–Snare Foundation",
"beginner-2":"Boots and Cats",
"beginner-3":"Boots and Cats, Doubled",
"beginner-4":"Straight Eights",
"beginner-5":"Double-Snare Turnaround",
"beginner-6":"Bmg Backbeat",

"wunknown-intermediate-1":"Sixteenth Hat Bed",
"wunknown-intermediate-2":"K–F Hat Weave",
"wunknown-intermediate-3":"Bdb Kick-Roll Groove",
"wunknown-intermediate-4":"Bdb Chain",
"wunknown-intermediate-5":"Snare-Led Bdb Chain",
"wunknown-intermediate-6":"Kick–Kick, Snare–Snare",
"wunknown-intermediate-7":"Peh Snare Turnaround",
"wunknown-intermediate-8":"Peh and PF Alternation",
"wunknown-intermediate-9":"Open Slot Groove",
"wunknown-intermediate-10":"tkK Triplet Drive",
"wunknown-intermediate-11":"Pfd Double-Time Run",
"wunknown-intermediate-12":"Peh Three-Step",
"wunknown-intermediate-13":"Kickless Hat Study",
"wunknown-intermediate-14":"Peh Rollover",

"wunknown-advanced-1":"Peh Backbeat",
"wunknown-advanced-2":"K Snare Ladder",
"wunknown-advanced-3":"tk Sixteenth Machine",
"wunknown-advanced-4":"Doubled-Kick Sixteenths",
"wunknown-advanced-5":"Bdb and tkK Interlock",
"wunknown-advanced-6":"Peh Interlock",
"wunknown-advanced-7":"Peh–tkK Cascade",
"wunknown-advanced-8":"Bdb Triplet Loop",
"wunknown-advanced-9":"Lip-Roll Bookends",
"wunknown-advanced-10":"Duck Snare Groove",
"wunknown-advanced-11":"b–f tkK Alternation",
"wunknown-advanced-12":"Peh Chain",
"wunknown-advanced-13":"PK Turnaround",
"wunknown-advanced-14":"PK–Peh Long Run",

"cj-1":"TkK Foundation",
"cj-2":"Bb Kk Insert",
"cj-3":"Bb Kk Double Insert",
"cj-4":"Bb Kk Cascade",
"cj-5":"Mixed Peh Cascade",
"cj-6":"kk Ostinato",
"cj-7":"kk and Peh Ostinato",
"cj-8":"Click and Q Groove",
"cj-9":"Lip Click Groove",
"cj-10":"Sucker Punch Clicks",

"helium-1":"Kch Foundation",
"helium-2":"Ps–Db Opening",
"helium-3":"t(t) Flam Groove",
"helium-4":"t(t) Flam, Tighter",
"helium-5":"Kch–t Sixteenth Run",
"helium-6":"Peh Inside Kch",
"helium-7":"Ft Hat Weave",
"helium-8":"Double-Hat Kch Bar",
"helium-9":"Double-Hat Kch Bar, Take Two",
"helium-10":"Ps–D–B Cell",
"helium-11":"Ps–D–B Cell with Hats",
"helium-12":"Kch Pair Ladder",
"helium-13":"Kch Pair Ladder, Inverted",
"helium-14":"Kch–t–b Rotation",
"helium-15":"Kch Rotation, Long",
"helium-16":"Bt–Ft Mirror",
"helium-17":"Bt Mirror",
"helium-18":"Ft(t) Weave",
"helium-19":"K–Kch–D Cycle",
"helium-20":"Bdpf Turnaround",
"helium-21":"Bb–Peh Alternation",
"helium-22":"Bb–Peh Alternation, Variant",
"helium-23":"Pf–Kch Long Cycle",
"helium-24":"Pf–Peh Long Cycle",
"helium-25":"B–Pf Kch Shuttle",
"helium-26":"Ps–D Peh Shuttle",
"helium-27":"Three-Cell Kch Loop",
"helium-28":"Ps–D Triple Cell",
"helium-29":"t(t) Four-Cell",
"helium-30":"t(t) Inside Kch",
"helium-31":"K–Kch Shuttle",
"helium-32":"K–Kch with Dz Tag",
"helium-33":"Peh–K–Kch Run",
"helium-34":"I–V Inward Run",
"helium-35":"Tb–Ft Kch Marathon",
"helium-36":"Pf–Db Marathon",
"helium-37":"K–Kch–D with Dz Tag",
"helium-38":"Tk–Kch Ladder",
"helium-39":"Bdb–Bdpf Run",
"helium-40":"Pf–Kch Rotation",
"helium-41":"Fft(t) Tag",
"helium-42":"Bbt(t) Tag",
"helium-43":"Peh–Kch Marathon",
"helium-44":"Peh–Kch Marathon, Variant",
"helium-45":"Iv Ostinato",
"helium-46":"Dbt(t) Two-Bar",
"helium-47":"Bdb Two-Bar",
"helium-48":"Dbt(t) Short Cell",
"helium-49":"Bk–Peh Repeat Block",
"helium-50":"Tft(t) Two-Bar",
}
# Patterns whose source text ran an explanatory legend into the notation line.
LEGENDS = {
"wunknown-intermediate-9":(["X = any sound you feel fits","Bm = bass kick"],"B (X) Bm t K t K (tkK)"),
"wunknown-advanced-10":(["(KQ) = K snare with a duck sound (big brr)"],
  "tkK bk (KQ) bk K Peh K b tkK kK btk (KQ) bk K Peh K"),
}
